#spring.mvc.view.prefix=/WEB-INF/views/
#spring.mvc.view.suffix=.jsp
##spring.mvc.static-path-pattern=/static/**
#
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.datasource.url=jdbc:mysql://localhost:3306/dbtest?serverTimezone=Asia/Seoul
#spring.datasource.username=ssafy
#spring.datasource.password=ssafy
#
#mybatis.config-location=classpath:/config/mybatis_config.xml
#mybatis.type-aliases-package=com.ssafy.sub.dto
#
#logging.level.root=info
#logging.file.name=./log/local
#
#spring.mail.host=smtp.gmail.com
#spring.mail.port=587
#spring.mail.username= ksb940925@gmail.com 
#spring.mail.password=xgctlnmvobaglcsc
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.timeout=5000
#spring.mail.properties.mail.smtp.starttls.enable=true

spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url : jdbc:mysql://localhost:3306/dbtest?serverTimezone=Asia/Seoul
    username : root
    password : ssafy
  mail:
    host : smtp.gmail.com
    port : 587
    username : ksb940925@gmail.com
    password : xgctlnmvobaglcsc
    properties:
      mail:
        smtp:
          auth : true
          timeout : 5000
          starttls:
            enable : true    
mybatis:
  config-location: classpath:/config/mybatis_config.xml
  type-aliases-package: com.ssafy.sub.dto
  
logging:
  level:
    root: info
  file:
    name: ./log/local
    
 #spring.jpa.hibernate.ddl-auto
